#!/usr/bin/env bash
# Script to list users, user IDs, and home directories from /etc/passwd
while IFS=: read -r usernm paswd usid gpid info home bash 
do
	echo "The user $usernm is part of the $gpid gang, lives in $home and rides $bash. $usid place is protected by the passcode $paswd, more info about the user here: $info"
done < /etc/passwd
