#!/usr/bin/env bash
# Script to display formatted user information from /etc/passwd

while IFS=: read -r usernm paswd usid gpid info home bash 
do
	echo "The user $usernm is part of the $gpid gang, lives in $home and rides $bash. $usid's place is protected by the passcode $paswd, more info about the user here: $info"
done < /etc/passwd
