#!/usr/bin/env bash
# using while loop to output "Best School" 10 times, and "Hi" when num is 8

num=0

while [ $num -lt 10 ] 

do
    if [ $num -eq 8 ]; then
        echo "Hi "
    else
        echo "Best School "
    
    fi
    
    num=$((num + 1))

done
