#!/usr/bin/env bash
# using while loop to output "Best School" 10 times, and "Hi" when num is 8

num=1

while [ $num -lt 11 ] 
do
    if [ $num -eq 4 ]; then
	    echo "bad luck"
	    num=$((num + 1))
	    continue
    fi

    if [ $num -eq 8 ]; then
	    echo "good luck"
	    num=$((num + 1))
	    continue
    fi

    echo "Best School"
    num=$((num + 1))
done
